// <auto-generated />
using System;
using Hitman.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hitman.Migrations
{
    [DbContext(typeof(HitsDbContext))]
    [Migration("20210622183536_Restore")]
    partial class Restore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hitman.Database.Models.HitData", b =>
                {
                    b.Property<int>("HitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Bounty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("HirerPlayerId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TargetPlayerId")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("TimePlaced")
                        .HasColumnType("datetime(6)");

                    b.HasKey("HitId");

                    b.ToTable("Hits");
                });
#pragma warning restore 612, 618
        }
    }
}
