// <auto-generated />
using System;
using Hitman.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hitman.Migrations
{
    [DbContext(typeof(HitsDbContext))]
    partial class HitsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hitman.Database.Models.HitData", b =>
                {
                    b.Property<int>("HitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Bounty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HirerPlayerId")
                        .HasColumnType("text");

                    b.Property<string>("TargetPlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimePlaced")
                        .HasColumnType("datetime");

                    b.HasKey("HitId");

                    b.ToTable("Hits");
                });
#pragma warning restore 612, 618
        }
    }
}
