name: Create Release Draft

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin Version'
        required: true

jobs:
  build:
    name: GitHub Release v${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    
    env:
      PLUGIN_NAME: "${{ github.event.repository.name }}"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Update versions
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ github.event.inputs.version }}</Version>#\" \"${{ env.PLUGIN_NAME }} - OpenMod/${{ env.PLUGIN_NAME }} - OpenMod.csproj\""
    
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish --configuration Release --no-restore -o Publish
      
    - name: Install zip
      run: sudo apt-get install zip
      
    - name: Zip OpenMod release artifacts
      run: |
        mkdir -p ./OpenMod/Plugins ./OpenMod/Libraries
        cd Publish
        mv "${{ env.PLUGIN_NAME }}.dll" ../OpenMod/Plugins
        mv product.json ../OpenMod
        rm -f 0Harmony.dll Autofac.dll Autofac.Extensions.DependencyInjection.dll Contrib.Bcl.Ranges.dll Cronos.dll \
          dnlib.dll DotNet.Glob.dll InlineIL.dll JetBrains.Annotations.dll Microsoft.Bcl.AsyncInterfaces.dll \
          Microsoft.Bcl.HashCode.dll Microsoft.DotNet.PlatformAbstractions.dll \
          Microsoft.Extensions.Configuration.Abstractions.dll Microsoft.Extensions.Configuration.Binder.dll \
          Microsoft.Extensions.Configuration.CommandLine.dll Microsoft.Extensions.Configuration.dll \
          Microsoft.Extensions.Configuration.EnvironmentVariables.dll Microsoft.Extensions.Configuration.FileExtensions.dll \
          Microsoft.Extensions.Configuration.Json.dll Microsoft.Extensions.Configuration.UserSecrets.dll \
          Microsoft.Extensions.DependencyInjection.Abstractions.dll Microsoft.Extensions.DependencyInjection.dll \
          Microsoft.Extensions.DependencyModel.dll Microsoft.Extensions.FileProviders.Abstractions.dll \
          Microsoft.Extensions.FileProviders.Physical.dll Microsoft.Extensions.FileSystemGlobbing.dll \
          Microsoft.Extensions.Hosting.Abstractions.dll Microsoft.Extensions.Hosting.dll \
          Microsoft.Extensions.Localization.Abstractions.dll Microsoft.Extensions.Localization.dll \
          Microsoft.Extensions.Logging.Abstractions.dll Microsoft.Extensions.Logging.Configuration.dll \
          Microsoft.Extensions.Logging.Console.dll Microsoft.Extensions.Logging.Debug.dll \
          Microsoft.Extensions.Logging.dll Microsoft.Extensions.Logging.EventLog.dll \
          Microsoft.Extensions.Logging.EventSource.dll Microsoft.Extensions.Options.ConfigurationExtensions.dll \
          Microsoft.Extensions.Options.dll Microsoft.Extensions.Primitives.dll Microsoft.Win32.Primitives.dll \
          MoreLinq.dll NetEscapades.Configuration.Yaml.dll netstandard.dll Newtonsoft.Json.dll \
          Nito.AsyncEx.Context.dll Nito.AsyncEx.Tasks.dll Nito.Disposables.dll NuGet.*.dll \
          OpenMod.Analyzers.dll OpenMod.API.dll OpenMod.Common.dll OpenMod.Core.dll \
          OpenMod.Extensions.Economy.Abstractions.dll OpenMod.Extensions.Games.Abstractions.dll \
          OpenMod.NuGet.dll OpenMod.Runtime.dll OpenMod.UnityEngine.dll OpenMod.Unturned.dll \
          OpenMod.Unturned.Module.Bootstrapper.dll OpenMod.Unturned.Module.Dev.dll OpenMod.Unturned.Module.Shared.dll \
          ReadLine.dll Rocket.API.dll Rocket.Core.dll Rocket.Unturned.dll RuntimeNullables.dll Semver.dll \
          Serilog.dll Serilog.Extensions.Hosting.dll Serilog.Extensions.Logging.dll Serilog.Settings.Configuration.dll \
          Serilog.Sinks.Async.dll Serilog.Sinks.Console.dll Serilog.Sinks.File.dll \
          SmartFormat.dll System.*.dll UniTask.dll UniTask.Linq.dll YamlDotNet.dll \
          Assembly-CSharp.dll SDG.*.dll Steamsworks.*.dll SystemEx.dll UnityEx.dll
        mv *.dll ../OpenMod/Libraries
        cd ../OpenMod
        zip -qr ./Release.zip *
        cd ..
      shell: bash
    
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: "${{ env.PLUGIN_NAME }} Release v${{ github.event.inputs.version }}"
        draft: true
        prerelease: false
        
    - name: Upload OpenMod release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./OpenMod/Release.zip
        asset_name: "${{ env.PLUGIN_NAME }}-OpenMod-v${{ github.event.inputs.version }}.zip"
        asset_content_type: application/zip
